version: '3.8'

services:
  # Override Guacamole to remove external port exposure
  guacamole:
    ports: []
    networks:
      - appliance_network
    # Only expose internally
    expose:
      - "8080"
      
  # Update nginx to proxy Guacamole requests
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/guacamole-internal.conf:/etc/nginx/conf.d/guacamole-internal.conf:ro