services:
  # MariaDB Database
  database:
    image: mariadb:latest
    container_name: ${DB_CONTAINER_NAME:-appliance_db}
    restart: always
    # Datenbank sollte niemals von außen erreichbar sein
    # ports:
    #   - "${DB_EXTERNAL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/database:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - ${NETWORK_NAME:-appliance_network}
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root --password=\"${MYSQL_ROOT_PASSWORD}\" || exit 1"]
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-20}
      start_period: 40s

  # Node.js Backend API with SSH Support
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME:-appliance_backend}
    restart: always
    # Backend sollte nur intern erreichbar sein (Production)
    # Für Entwicklung: Port aktivieren
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      # Database Configuration
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # Security
      JWT_SECRET: ${JWT_SECRET}
      SSH_KEY_ENCRYPTION_SECRET: ${SSH_KEY_ENCRYPTION_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      NODE_ENV: ${NODE_ENV:-production}
      # CORS Settings
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      # SSH Configuration
      SSH_TOOLS_ENABLED: ${SSH_TOOLS_ENABLED:-true}
      SSH_AUTO_INIT: ${SSH_AUTO_INIT:-true}
      # Guacamole Integration
      GUACAMOLE_URL: ${GUACAMOLE_URL}
      GUACAMOLE_PROXY_URL: ${GUACAMOLE_PROXY_URL}
      GUACAMOLE_DB_HOST: ${GUACAMOLE_DB_HOST:-appliance_guacamole_db}
      GUACAMOLE_DB_NAME: ${GUACAMOLE_DB_NAME:-guacamole_db}
      GUACAMOLE_DB_USER: ${GUACAMOLE_DB_USER:-guacamole_user}
      GUACAMOLE_DB_PASSWORD: ${GUACAMOLE_DB_PASSWORD:-guacamole_pass123}
      # External URL for remote access
      EXTERNAL_URL: ${EXTERNAL_URL}
      # Features
      FEATURE_AUDIT_LOG: ${FEATURE_AUDIT_LOG:-true}
      FEATURE_BACKUP_RESTORE: ${FEATURE_BACKUP_RESTORE:-true}
      FEATURE_SSH_TERMINAL: ${FEATURE_SSH_TERMINAL:-true}
      FEATURE_SERVICE_CONTROL: ${FEATURE_SERVICE_CONTROL:-true}
      FEATURE_USER_MANAGEMENT: ${FEATURE_USER_MANAGEMENT:-true}
      FEATURE_REMOTE_DESKTOP: ${FEATURE_REMOTE_DESKTOP:-true}
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FORMAT: ${LOG_FORMAT:-combined}
      # Docker host access
      DOCKER_HOST_INTERNAL: 'true'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - ${NETWORK_NAME:-appliance_network}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data/ssh_keys:/root/.ssh
      - ./data/uploads:/app/uploads
      # Shared temp directory für Terminal-Sessions
      - ./data/terminal_sessions:/tmp/terminal-sessions
      # Docker socket for container management
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Optional: Mount lokales SSH-Keys Verzeichnis für Entwicklung
      # - ./ssh-keys:/root/.ssh
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:3001/api/health && which ssh && which ssh-copy-id && which sshpass"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 40s

  # Nginx Web Server with custom image
  webserver:
    build: ./nginx
    container_name: ${WEBSERVER_CONTAINER_NAME:-appliance_webserver}
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-9080}:80"
      - "${NGINX_HTTPS_PORT:-9443}:443"
    volumes:
      # Mount frontend build - writable for updates
      - ./frontend/build:/usr/share/nginx/html
      # Override conf.d if needed for development
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - ttyd
      # Guacamole is optional - webserver should start without it
    networks:
      - ${NETWORK_NAME:-appliance_network}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}

  # ttyd Web Terminal
  ttyd:
    build: ./ttyd
    container_name: ${TTYD_CONTAINER_NAME:-appliance_ttyd}
    restart: always
    # ttyd läuft über nginx proxy auf /terminal/
    # ports:
    #   - "${TTYD_PORT:-7681}:7681"
    command: >
      ttyd
      --writable
      --port 7681
      --base-path /
      --terminal-type xterm-256color
      /scripts/ttyd-ssh-wrapper.sh
    environment:
      # Nur Port als Standard, keine Host/User Defaults mehr
      SSH_PORT: ${TTYD_DEFAULT_PORT:-22}
    networks:
      - ${NETWORK_NAME:-appliance_network}
    volumes:
      # SSH-Keys für Terminal-Zugriff
      - ./data/ssh_keys:/root/.ssh
      # Optional: Shared scripts
      - ./scripts:/scripts:ro
      # Shared temp directory für Session-Dateien
      - ./data/terminal_sessions:/tmp/terminal-sessions
    healthcheck:
      test: ["CMD", "sh", "-c", "pidof ttyd || exit 1"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}

  # ====================================================================
  # REMOTE DESKTOP SERVICES (GUACAMOLE)
  # ====================================================================
  
  # Guacamole Proxy Daemon
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: ${GUACD_CONTAINER_NAME:-appliance_guacd}
    restart: always
    volumes:
      - ./data/guacamole_drive:/drive:rw
      - ./data/guacamole_record:/record:rw
    environment:
      GUACD_LOG_LEVEL: ${GUACD_LOG_LEVEL:-warning}
      # Performance Tuning
      GUACD_MAX_THREADS: 8
      GUACD_BIND_HOST: 0.0.0.0
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    networks:
      - ${NETWORK_NAME:-appliance_network}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4822"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}

  # Guacamole PostgreSQL Database
  guacamole-postgres:
    image: postgres:15-alpine
    container_name: ${GUACAMOLE_DB_CONTAINER_NAME:-appliance_guacamole_db}
    restart: always
    environment:
      POSTGRES_DB: ${GUACAMOLE_DB_NAME:-guacamole_db}
      POSTGRES_USER: ${GUACAMOLE_DB_USER:-guacamole_user}
      POSTGRES_PASSWORD: ${GUACAMOLE_DB_PASSWORD:-guacamole_pass123}
    volumes:
      - ./data/guacamole_db:/var/lib/postgresql/data
      - ./guacamole/001-create-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./guacamole/002-create-admin-user.sql:/docker-entrypoint-initdb.d/02-admin.sql:ro
      - ./guacamole/custom-sftp.sql:/docker-entrypoint-initdb.d/03-custom-sftp.sql:ro
    networks:
      - ${NETWORK_NAME:-appliance_network}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GUACAMOLE_DB_USER:-guacamole_user}"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}

  # Guacamole Web Application
  guacamole:
    build: ./guacamole
    container_name: ${GUACAMOLE_CONTAINER_NAME:-appliance_guacamole}
    restart: always
    depends_on:
      guacd:
        condition: service_healthy
      guacamole-postgres:
        condition: service_healthy
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: guacamole-postgres
      POSTGRES_DATABASE: ${GUACAMOLE_DB_NAME:-guacamole_db}
      POSTGRES_USER: ${GUACAMOLE_DB_USER:-guacamole_user}
      POSTGRES_PASSWORD: ${GUACAMOLE_DB_PASSWORD:-guacamole_pass123}
      # Integration settings - DISABLED for token auth
      # HEADER_ENABLED: 'true'
      # HTTP_AUTH_HEADER: 'REMOTE_USER'
      # CORS für iFrame
      EXTENSION_PRIORITY: '*'
      # Optional: Custom settings
      GUACAMOLE_HOME: /etc/guacamole
      # JWT Settings für Extension
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # Standard SSH-Zugangsdaten für SFTP
      DEFAULT_SSH_USER: ${DEFAULT_SSH_USER:-alflewerken}
      DEFAULT_SSH_PASS: ${DEFAULT_SSH_PASS:-}
    volumes:
      - ./data/guacamole_home:/etc/guacamole
    # Port wird nicht nach außen geöffnet - nur über nginx erreichbar
    # ports:
    #   - "${GUACAMOLE_PORT:-9070}:8080"
    networks:
      appliance_network:
        aliases:
          - guacamole-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/guacamole/"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 60s

  # ====================================================================
  # RUSTDESK SERVICES
  # ====================================================================
  
  # RustDesk ID/Rendezvous Server
  rustdesk-server:
    image: rustdesk/rustdesk-server:latest
    container_name: ${RUSTDESK_SERVER_CONTAINER:-rustdesk-server}
    command: hbbs
    restart: always
    environment:
      - RELAY=0.0.0.0:21117
      - PORT=21116
    ports:
      - "${RUSTDESK_ID_PORT:-21216}:21116"  # ID Server TCP (external:internal)
      - "${RUSTDESK_ID_PORT:-21216}:21116/udp"  # ID Server UDP
      - "${RUSTDESK_WEB_PORT:-21218}:21118"  # Web Client (21218 extern -> 21118 intern)
      - "${RUSTDESK_API_PORT:-21219}:21119"  # API (21219 extern -> 21119 intern)
    volumes:
      - ./data/rustdesk:/root
    networks:
      - ${NETWORK_NAME:-appliance_network}
    # Removed healthcheck - RustDesk container has no shell or common tools

  # RustDesk Relay Server
  rustdesk-relay:
    image: rustdesk/rustdesk-server:latest
    container_name: ${RUSTDESK_RELAY_CONTAINER:-rustdesk-relay}
    command: hbbr
    restart: always
    ports:
      - "${RUSTDESK_RELAY_PORT:-21217}:21117"  # Relay Server (21217 extern -> 21117 intern)
      - "${RUSTDESK_WEBSOCKET_PORT:-21220}:21120"  # Websocket (21220 extern -> 21120 intern)
    volumes:
      - ./data/rustdesk:/root
    networks:
      - ${NETWORK_NAME:-appliance_network}
    # Removed healthcheck - RustDesk container has no shell or common tools



# ====================================================================
# VOLUMES
# ====================================================================
volumes:
  # Main application data
  db_data:
    driver: local
    labels:
      - "backup=${BACKUP_ENABLED:-true}"
      - "purpose=database"
      - "project=web-appliance-dashboard"
      
  ssh_keys:
    driver: local
    labels:
      - "backup=${BACKUP_ENABLED:-true}"
      - "purpose=ssh-keys"
      - "project=web-appliance-dashboard"
      
  uploads:
    driver: local
    labels:
      - "backup=${BACKUP_ENABLED:-true}"
      - "purpose=uploads"
      - "project=web-appliance-dashboard"
      
  terminal_sessions:
    driver: local
    labels:
      - "backup=${BACKUP_ENABLED:-false}"
      - "purpose=terminal-sessions"
      - "project=web-appliance-dashboard"

  # Guacamole volumes
  guacamole_db:
    driver: local
    labels:
      - "backup=${BACKUP_ENABLED:-true}"
      - "purpose=guacamole-database"
      - "project=web-appliance-dashboard"
      
  guacamole_drive:
    driver: local
    labels:
      - "backup=${BACKUP_ENABLED:-false}"
      - "purpose=guacamole-file-transfer"
      - "project=web-appliance-dashboard"
      
  guacamole_record:
    driver: local
    labels:
      - "backup=${BACKUP_ENABLED:-false}"
      - "purpose=guacamole-session-recording"
      - "project=web-appliance-dashboard"
      

# ====================================================================
# NETWORKS
# ====================================================================
networks:
  appliance_network:
    name: ${NETWORK_NAME:-appliance_network}
    driver: bridge
    labels:
      - "project=web-appliance-dashboard"
      - "environment=${NODE_ENV:-production}"