#!/bin/bash

# Script to translate German comments in api-client-sdks-eng.md

echo "📝 Translating German comments in api-client-sdks-eng.md..."

cd "$(dirname "$0")/../docs" || exit 1

# Create a temporary file
temp_file="api-client-sdks-eng.tmp"
cp api-client-sdks-eng.md "$temp_file"

# Common German -> English translations
declare -A translations=(
    ["Verwendung"]="Usage"
    ["Beispiel"]="Example"
    ["Fehlerbehandlung"]="Error Handling"
    ["Installation"]="Installation"
    ["Konfiguration"]="Configuration"
    ["Authentifizierung"]="Authentication"
    ["Verbindung"]="Connection"
    ["Antwort"]="Response"
    ["Anfrage"]="Request"
    ["Erstellen"]="Create"
    ["Aktualisieren"]="Update"
    ["Löschen"]="Delete"
    ["Abrufen"]="Retrieve"
    ["Parameter"]="Parameters"
    ["Rückgabewert"]="Return Value"
    ["Fehler"]="Error"
    ["Erfolgreich"]="Successful"
    ["Fehlgeschlagen"]="Failed"
    ["Benutzer"]="User"
    ["Passwort"]="Password"
    ["Schlüssel"]="Key"
    ["Token"]="Token"
    ["Sitzung"]="Session"
    ["Verwaltung"]="Management"
    ["Steuerung"]="Control"
    ["Dienst"]="Service"
    ["Server"]="Server"
    ["Client"]="Client"
    ["Datei"]="File"
    ["Ordner"]="Folder"
    ["Backup"]="Backup"
    ["Wiederherstellung"]="Restore"
    ["Echtzeit"]="Real-time"
    ["Ereignisse"]="Events"
    ["Nachricht"]="Message"
    ["Status"]="Status"
    ["Protokoll"]="Log"
    ["Überwachung"]="Monitoring"
    ["Sicherheit"]="Security"
    ["Berechtigung"]="Permission"
    ["Rolle"]="Role"
    ["Gruppe"]="Group"
    ["Einstellungen"]="Settings"
    ["Konfigurationsdatei"]="Configuration File"
    ["Umgebungsvariablen"]="Environment Variables"
    ["Standardwert"]="Default Value"
    ["Optional"]="Optional"
    ["Erforderlich"]="Required"
    ["Beschreibung"]="Description"
    ["Hinweis"]="Note"
    ["Warnung"]="Warning"
    ["Wichtig"]="Important"
    ["Siehe auch"]="See also"
    ["Weitere Informationen"]="More Information"
    ["Dokumentation"]="Documentation"
    ["API-Referenz"]="API Reference"
    ["Beispielcode"]="Example Code"
    ["Vollständiges Beispiel"]="Complete Example"
    ["Erweiterte Funktionen"]="Advanced Features"
    ["Basis-Client"]="Basic Client"
    ["TypeScript Version"]="TypeScript Version"
    ["Mit Fehlerbehandlung"]="With Error Handling"
    ["Asynchrone Operationen"]="Asynchronous Operations"
    ["WebSocket-Verbindung"]="WebSocket Connection"
    ["SSE-Verbindung"]="SSE Connection"
    ["Datei-Upload"]="File Upload"
    ["Datei-Download"]="File Download"
    ["Stream-Verarbeitung"]="Stream Processing"
    ["Batch-Operationen"]="Batch Operations"
    ["Pagination"]="Pagination"
    ["Sortierung"]="Sorting"
    ["Filterung"]="Filtering"
    ["Suche"]="Search"
    ["Export"]="Export"
    ["Import"]="Import"
    ["Validierung"]="Validation"
    ["Formatierung"]="Formatting"
    ["Konvertierung"]="Conversion"
    ["Verschlüsselung"]="Encryption"
    ["Entschlüsselung"]="Decryption"
    ["Komprimierung"]="Compression"
    ["Dekomprimierung"]="Decompression"
    ["Cache"]="Cache"
    ["Session-Management"]="Session Management"
    ["Token-Verwaltung"]="Token Management"
    ["Retry-Logik"]="Retry Logic"
    ["Rate-Limiting"]="Rate Limiting"
    ["Timeout-Behandlung"]="Timeout Handling"
    ["Proxy-Konfiguration"]="Proxy Configuration"
    ["SSL/TLS-Konfiguration"]="SSL/TLS Configuration"
    ["Header-Manipulation"]="Header Manipulation"
    ["Request-Interceptor"]="Request Interceptor"
    ["Response-Interceptor"]="Response Interceptor"
    ["Middleware"]="Middleware"
    ["Plugin-System"]="Plugin System"
    ["Event-Handler"]="Event Handler"
    ["Callback-Funktionen"]="Callback Functions"
    ["Promise-basiert"]="Promise-based"
    ["Async/Await"]="Async/Await"
    ["Observable-Pattern"]="Observable Pattern"
    ["Reactive Programming"]="Reactive Programming"
)

# Replace German words with English
for german in "${!translations[@]}"; do
    english="${translations[$german]}"
    sed -i.bak "s/\b$german\b/$english/g" "$temp_file"
done

# Replace the original file
mv "$temp_file" api-client-sdks-eng.md
rm -f api-client-sdks-eng.md.bak

echo "✅ Translation completed for api-client-sdks-eng.md"
